#!/bin/bash
sudo apt update
git clone https://github.com/ExpertAnonymous/PhoneInfoga.git
git clone https://github.com/Greenwolf/social_mapper.git
git clone https://github.com/h4ck3r0/kali-theme.git
git clone https://github.com/devXprite/infoooze.git
git clone https://github.com/SNGWN/Burp-Suite.git
git clone https://github.com/Und3rf10w/kali-anonsurf.git
git clone https://github.com/trimstray/multitor.git
git clone https://github.com/nmap/nmap.git
git clone https://github.com/screetsec/Dracnmap.git
git clone https://github.com/LionSec/xerosploit.git
git clone https://github.com/Tuhinshubhra/RED_HAWK.git
git clone https://github.com/bhavsec/reconspider.git
git clone https://github.com/m4ll0k/Infoga.git
git clone https://github.com/s0md3v/ReconDog.git
git clone https://github.com/s0md3v/Striker.git
git clone https://github.com/floriankunushevci/rang3r.git
git clone https://github.com/m4ll0k/SecretFinder.git
git clone https://github.com/joeyagreco/ranger-reloaded.git
git clone https://github.com/s0md3v/Breacher.git
git clone https://github.com/Mebus/cupp.git
git clone https://github.com/Z4nzu/wlcreator.git
git clone https://github.com/UndeadSec/GoblinWordGenerator.git
git clone https://github.com/Viralmaniar/SMWYG-Show-Me-What-You-Got.git
git clone https://github.com/P0cL4bs/wifipumpkin3.git
git clone https://github.com/wiire-a/pixiewps.git
git clone https://github.com/andrewmichaelsmith/bluepot.git
git clone https://github.com/thehackingsage/fluxion.git
git clone https://github.com/wifiphisher/wifiphisher.git
git clone https://github.com/wifiphisher/wifiphisher.git
git clone https://github.com/derv82/wifite2.git
git clone https://github.com/Z4nzu/fakeap.git
git clone https://github.com/Z4nzu/fastssh.git
git clone https://github.com/sqlmapproject/sqlmap.git
git clone https://github.com/UndeadSec/SocialFish.git
git clone https://github.com/kgretzky/evilginx2.git
git clone https://github.com/telekom-security/explo.git
git clone https://github.com/JohnTroony/Blisqy.git
git clone https://github.com/utkusen/leviathan.git
git clone https://github.com/Cvar1984/sqlscan.git
git clone https://github.com/trustedsec/social-engineer-toolkit.git
git clone https://github.com/UndeadSec/SocialFish.git
git clone https://github.com/hangetzzu/saycheese.git
git clone https://github.com/Viralmaniar/I-See-You.git
git clone https://github.com/cryptedwolf/ohmyqr.git
git clone https://github.com/An0nUD4Y/shellphish.git
git clone https://github.com/iinc0gnit0/BlackPhish.git
git clone https://github.com/jaeles-project/gospider.git
git clone https://github.com/chinarulezzz/pixload.git
git clone https://github.com/UndeadSec/Debinject.git
git clone https://github.com/iojw/socialscan.git
git clone https://github.com/sherlock-project/sherlock.git
git clone https://github.com/Greenwolf/social_mapper.git
git clone https://github.com/xHak9x/finduser.git
git clone https://github.com/aryanrtm/KawaiiDeauther.git
git clone https://github.com/MisterBianco/wifijammer-ng.git
git clone https://github.com/s0md3v/Hash-Buster.git
git clone https://github.com/4w4k3/KnockMail.git
git clone https://github.com/UndeadSec/EvilURL.git
git clone https://github.com/HatBashBR/HatCloud.git
git clone https://github.com/Ro9ueAdmin/EvilApp.git
git clone https://github.com/kinghacker0/WishFish.git
git clone https://github.com/JasonJerry/lockphish.git
git clone https://github.com/papusingh2sms/mysms.git
git clone https://github.com/F4dl0/keydroid.git
git clone https://github.com/jakuta-tech/underhanded.git
git clone https://github.com/Matrix07ksa/Brute_Force.git
git clone https://github.com/Matrix07ksa/Brute_Force.git
git clone https://github.com/chinoogawa/instaBrute.git
git clone https://github.com/W1LDN16H7/StegoCracker.git
git clone https://github.com/iinc0gnit0/RVuln.git
git clone https://github.com/s0md3v/XSStrike.git
git clone https://github.com/Ekultek/XanXSS.git
git clone https://github.com/menkrep1337/XSSCon.git
git clone https://github.com/hahwul/XSpear.git
git clone https://github.com/capture0x/XSS-LOADER.git
git clone https://github.com/Damian89/extended-xss-search.git
git clone https://github.com/hahwul/dalfox.git
git clone https://github.com/knassar702/pyshell.git
git clone https://github.com/nathanlopez/Stitch.git
git clone https://github.com/jseidl/GoldenEye.git
git clone https://github.com/epsylon/ufonet.git
git clone https://github.com/fatihsnsy/aSYNcrone.git
git clone https://github.com/aboul3la/Sublist3r.git
git clone https://github.com/santatic/web2attack.git
git clone https://github.com/UndeadSec/checkURL.git
git clone https://github.com/s0md3v/Blazy.git
git clone https://github.com/m4ll0k/takeover.git
git clone https://gitlab.com/kalilinux/packages/dirb.git
git clone https://github.com/screetsec/Vegile.git
git clone https://github.com/UndeadSec/HeraKeylogger.git
git clone https://github.com/simsong/bulk_extractor.git
git clone https://github.com/screetsec/TheFatRat.git
git clone https://github.com/g0tmi1k/msfpc.git
git clone https://github.com/screetsec/Brutal.git
git clone https://github.com/r00t-3xp10it/venom.git
git clone https://github.com/indexnotfound404/spycam.git
git clone https://github.com/kinghacker0/Mob-Droid.git
git clone https://github.com/UndeadSec/Enigma.git
git clone https://github.com/threat9/routersploit.git
git clone https://github.com/The404Hacking/websploit.git
git clone https://github.com/commixproject/commix.git
git clone https://github.com/santatic/web2attack.git
git clone https://github.com/androguard/androguard.git
git clone https://github.com/lxdvs/apk2gold.git
git clone https://github.com/skylot/jadx.git
git clone https://github.com/rajkumardusad/IP-Tracer.git
git clone https://github.com/xHak9x/fbi.git
git clone https://github.com/smicallef/spiderfoot.git
git clone https://github.com/Manisso/fsociety.git
git clone https://github.com/sleuthkit/autopsy.git
git clone https://github.com/p1ngul1n0/blackbird.git
git clone https://github.com/jofpin/trape.git
git clone https://github.com/secdev/scapy.git
git clone https://github.com/megadose/holehe.git
git clone https://github.com/megadose/toutatis.git
git clone https://github.com/daprofiler/DaProfiler.git
git clone https://github.com/blackeko/yesitsme.git
sudo apt update
